# Generated by Django 4.2 on 2026-04-08 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_reseña'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True, 'verbose_name': 'Colección / Categoría', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='favorito',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={'managed': True, 'verbose_name_plural': 'Lotes e Inventario'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True, 'verbose_name_plural': 'Pedidos de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True, 'verbose_name_plural': 'Productos (Catálogo)'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True, 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='reseña',
            options={'managed': True, 'verbose_name_plural': 'Reseñas de Productos'},
        ),
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Nombre del representante', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedido'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Colección'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterModelTable(
            name='reseña',
            table='core_reseña',
        ),
    ]
