# Generated by Django 4.2 on 2026-04-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_options_alter_favorito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reseña',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
