# Generated by Django 4.2 on 2026-04-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_favorito_options_alter_reseña_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reseña',
            options={'managed': True, 'verbose_name_plural': 'Reseñas de Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
    ]
