# Generated by Django 4.2 on 2026-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_favorito_options_alter_reseña_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para la tarjeta de colección en el inicio', null=True, upload_to='categorias/'),
        ),
    ]
